### ISSUE TITLE
getting error while running  utils.async_elasticsearch_retriever.py 

### ISSUE THREAD

**Issue by himanshushukla12** [GAIR-NLP/OpenResearcher#6]
`python -um utils.async_elasticsearch_retriever`

```[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/z004x2xz/OpenResearcher/venOR/lib/python3.10/sit
[nltk_data]     e-packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
Traceback (most recent call last):
  File "/home/z004x2xz/local/python3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/z004x2xz/local/python3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/z004x2xz/OpenResearcher/utils/async_elasticsearch_retriever.py", line 47, in <module>
    retriever = AsyncESRetriever(
  File "/home/z004x2xz/OpenResearcher/utils/async_elasticsearch_retriever.py", line 25, in __init__
    elastic_search_bm25 = ElasticsearchStore(
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/llama_index/vector_stores/elasticsearch/base.py", line 222, in __init__
    es_client = get_elasticsearch_client(
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/llama_index/vector_stores/elasticsearch/utils.py", line 47, in get_elasticsearch_client
    sync_es_client.info()  # use sync client so don't have to 'await' to just get info
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 2464, in info
    return self.perform_request(  # type: ignore[return-value]
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 271, in perform_request
    response = self._perform_request(
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 316, in _perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elastic_transport/_transport.py", line 342, in perform_request
    resp = node.perform_request(
  File "/home/z004x2xz/OpenResearcher/venOR/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7a7bfd8e4a90>: Failed to establish a new connection: [Errno 111] Connection refused))```


I followed all the steps corretly
I'm running using hugging-face models

**Comment by Zeetc** [comment]
Sorry for not providing clear instructions in the README. Before performing BM25 retrieval, please follow these steps:
1. Ensure Elasticsearch is installed and running. You can use Docker to install Elasticsearch.
2. Run `connector.meta_elastic.py` to preprocess data for BM25. Use the following command: `python -m connector.meta_elastic`
3. After preprocessing is complete, run the command: `python -m utils.async_elasticsearch_retriever`
Thanks!

**Comment by himanshushukla12** [comment]
can you please push the same details in `readme.MD`.  So that it will be easy for implementing the project. @Zeetc

**Comment by Zeetc** [comment]
Sure, we have updated the readme document. You can take a look at it.
